services:
  postgres_keycloak:
    image: postgres:latest
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_KEYCLOAK_USER}
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
      - ./keycloak-data/keycloak_backup.dump:/sql/keycloak_backup.dump
      - ./scripts/import_keycloak_data.sh:/docker-entrypoint-initdb.d/import_keycloak_data.sh
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - docker-backend

  postgres_ecommerce:
    image: postgres:latest
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ${PSQL_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      POSTGRES_DB: e_commerce
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/sql/init.sql
      - ./sql/users.sql:/sql/users.sql
      - ./sql/products.sql:/sql/products.sql
      - ./sql/product_images.sql:/sql/product_images.sql
      - ./sql/feature_bullets.sql:/sql/feature_bullets.sql
      - ./sql/reviews.sql:/sql/reviews.sql
      - ./sql/carts.sql:/sql/carts.sql
      - ./sql/cart_items.sql:/sql/cart_items.sql
      - ./sql/orders.sql:/sql/orders.sql
      - ./sql/order_lines.sql:/sql/order_lines.sql
      - ./sql/final_setup.sql:/sql/final_setup.sql
      - ./scripts/import_sql.sh:/docker-entrypoint-initdb.d/import_sql.sh
      - e_commerce_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - docker-backend

  keycloak:
    image: keycloak/keycloak:26.0.4
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_keycloak:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_KEYCLOAK_USER}
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: false
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
      KC_THEME: myTheme
    volumes:
      - ./scripts/keycloak_message_en.properties:/opt/keycloak/themes/myTheme/email/messages/messages_en.properties
      - ./scripts/keycloak_theme.properties:/opt/keycloak/themes/myTheme/email/theme.properties
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --features=scripts,docker
      #      - --import-realm
    #    volumes:
    #      - ./keycloak-data:/tmp/imports/
    #      - ./scripts/import_keycloak_data.sh:/tmp/script/import_keycloak_data.sh
    depends_on:
      postgres_keycloak:
        condition: service_healthy
    networks:
      - docker-backend

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - docker-backend

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    networks:
      - docker-backend

  elasticsearch:
    image: bitnami/elasticsearch:8.17.1
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/bitnami/elasticsearch
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
    ports:
      - "9300:9300"
      - "9200:9200"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s
    networks:
      - docker-backend

  kibana:
    image: bitnami/kibana:8.17.1
    container_name: kibana
    volumes:
      - kibana_data:/bitnami/kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - docker-backend

  logstash:
    image: bitnami/logstash:8.17.1
    container_name: logstash
    volumes:
      - logstash_data:/bitnami/logstash
      - ./logstash/pipeline/logstash.conf:/etc/logstash/conf.d/logstash.conf
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - "5000:5000"
    networks:
      - docker-backend

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    networks:
      - docker-backend

  config-server:
    build:
      context: ./configserver
      dockerfile: Dockerfile
    image: application/config-server:latest
    container_name: config-server
    ports:
      - "8085:8085"
    volumes:
      - .env:/app/.env
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 2
    networks:
      - docker-backend

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    image: application/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - docker-backend

  gateway-server:
    build:
      context: ./gatewayserver
      dockerfile: Dockerfile
    image: application/gatewayserver:latest
    container_name: gateway-server
    ports:
      - "8072:8072"
    volumes:
      - .env:/app/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - docker-backend

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    image: application/product-service:latest
    container_name: product-service
    ports:
      - "8090:8090"
    volumes:
      - .env:/app/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres_ecommerce:
        condition: service_started
      redis:
        condition: service_started
      kafka:
        condition: service_started
      elasticsearch:
        condition: service_started
      logstash:
        condition: service_started
      kibana:
        condition: service_started
    networks:
      - docker-backend

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    image: application/review-service:latest
    container_name: review-service
    ports:
      - "8091:8091"
    volumes:
      - .env:/app/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres_ecommerce:
        condition: service_started
      kafka:
        condition: service_started
      elasticsearch:
        condition: service_started
      logstash:
        condition: service_started
      kibana:
        condition: service_started
    networks:
      - docker-backend

  cart-service:
    build:
      context: ./cart-service
      dockerfile: Dockerfile
    image: application/cart-service:latest
    container_name: cart-service
    ports:
      - "8092:8092"
    volumes:
      - .env:/app/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres_ecommerce:
        condition: service_started
      kafka:
        condition: service_started
      elasticsearch:
        condition: service_started
      logstash:
        condition: service_started
      kibana:
        condition: service_started
    networks:
      - docker-backend

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: application/order-service:latest
    container_name: order-service
    ports:
      - "8093:8093"
    volumes:
      - .env:/app/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres_ecommerce:
        condition: service_started
      kafka:
        condition: service_started
      elasticsearch:
        condition: service_started
      logstash:
        condition: service_started
      kibana:
        condition: service_started
    networks:
      - docker-backend

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: application/user-service:latest
    container_name: user-service
    ports:
      - "8094:8094"
    volumes:
      - .env:/app/.env
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      postgres_keycloak:
        condition: service_started
      keycloak:
        condition: service_started
      postgres_ecommerce:
        condition: service_started
      kafka:
        condition: service_started
      elasticsearch:
        condition: service_started
      logstash:
        condition: service_started
      kibana:
        condition: service_started
    networks:
      - docker-backend

volumes:
  keycloak_data: {}
  e_commerce_data: {}
  redis_data: {}
  elasticsearch_data: {}
  kibana_data: {}
  logstash_data: {}

networks:
  docker-backend:
    driver: bridge