spring:
  application:
    name: gatewayserver
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,SetCookie
            - PreserveHostHeader=true
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
            - RewritePath=/review-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,SetCookie
            - PreserveHostHeader=true
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - RewritePath=/order-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,SetCookie
            - PreserveHostHeader=true
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/cart-service/**
          filters:
            - RewritePath=/cart-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,SetCookie
            - PreserveHostHeader=true
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,SetCookie
            - PreserveHostHeader=true
  #Zipkin Config
  zipkin:
    base-url: ${ZIPKIN_HOST:http://zipkin}:9411

#Eureka Configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registryFetchIntervalSeconds: 10
    waitTimeInMsWhenSyncEmpty: 5000  # Helps avoid the "cache refresh failed" warning
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:gatewayserver}  # Uses hostname, which works in both local & Docker

# Actuator Configuration
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: ${spring.zipkin.base-url}/api/v2/spans
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always
    tracing:
      enabled: true
    metrics:
      enabled: true
    gateway:
      enabled: true

#Server Configuration
server:
  port: 8072
