spring:
  application:
    name: product-service
  # Hibernate and JPA settings
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: POSTGRESQL
    properties:
      transaction:
        jta:
          platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  # Data source configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-test-query: SELECT 1
  sql:
    init:
      platform: postgres
#  OAuth2 settings
  security:
    oauth2:
      client:
      authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          issuer-uri:  ${keycloak.server-url}realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
# Cloud Configuration
  cloud:
    function:
      definition: inboundReviewChange # Functional definition for the Consumer
    stream:
      bindings:
        inboundReviewChange-in-0: # Functional input binding for the Consumer
          destination: reviewChangeTopic # Kafka topic to consume from
          group: reviewGroup # Consumer group for Kafka
          content-type: application/json # Deserializes JSON payload
    kafka:
      binder:
        brokers: ${KAFKA_HOST}:9092 # Kafka broker address
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
  #Zipkin Config
  zipkin:
    base-url: ${ZIPKIN_HOST}:9411

#JWT Configuration
jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_CLIENT_ID}
      principle-attribute: preferred_username

#Keycloak Configuration
keycloak:
  server-url: ${KEYCLOAK_URL}
  client-id: ${KEYCLOAK_CLIENT_ID}
#Eureka Configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        - http://eureka-server:8761/eureka/
        - http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 60
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
  bulkhead:
    instances:
      bulkheadProductService:
        maxConcurrentCalls: 10
        maxWaitDuration: 100ms
  retry:
    instances:
      retryProductService:
        maxAttempts: 3
        waitDuration: 10000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.lang.RuntimeException
  ratelimiter:
    instances:
      productService:
        timeoutDuration: 1000ms
        limitRefreshPeriod: 5000ms
        limitForPeriod: 5

#Logging Configuration
logstash:
  host: ${LOGSTASH_HOST}

#Server Configuration
server:
  port: 8090

#Redis Configuration
redis:
  server:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

# Actuator Configuration
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: ${spring.zipkin.base-url}/api/v2/spans
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
    enabled-by-default: true
  endpoint:
    health:
      enabled: true
      show-details: always
    tracing:
      enabled: true
    metrics:
      enabled: true
    gateway:
      enabled: true