spring:
  application:
    name: review-service
  # Hibernate and JPA settings
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      transaction:
        jta:
          platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
  # Data source configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-test-query: SELECT 1
  sql:
    init:
      platform: postgres
 # OAuth2 settings
  security:
    oauth2:
      client:
      authorization-grant-type: authorization_code
      resourceserver:
        jwt:
          issuer-uri:  ${keycloak.server-url}realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  #Cloud Configuration
  cloud:
    function:
      definition: supplyReviewChangeModel
    stream:
      poller:
        fixed-delay: 5000
        initial-delay: 1000
        max-messages-per-poll: 1
      bindings:
        supplyReviewChangeModel-out-0:
          destination: reviewChangeTopic
          content-type: application/json
    kafka:
      binder:
        brokers: localhost:9092
  kafka:
    bootstrap-servers: localhost:9092

#JWT Configuration
jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_CLIENT_ID}
      principle-attribute: preferred_username

#Keycloak Configuration
keycloak:
  server-url: ${KEYCLOAK_URL}
  client-id: ${KEYCLOAK_CLIENT_ID}

#Eureka Configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:
        - http://eureka-server:8761/eureka/
        - http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      reviewService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 5s
        failureRateThreshold: 60
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
  bulkhead:
    instances:
      bulkheadReviewService:
        maxConcurrentCalls: 10
        maxWaitDuration: 100ms
  retry:
    instances:
      retryReviewService:
        maxAttempts: 3
        waitDuration: 10000ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - java.lang.RuntimeException
  ratelimiter:
    instances:
      reviewService:
        timeoutDuration: 1000ms
        limitRefreshPeriod: 5000ms
        limitForPeriod: 5

server:
  port: 8091