spring:
  application:
    name: configserver
  profiles:
    active: ${CONFIG_PROFILE:native}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          uri: ${GIT_URI}
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}
  config:
    import: optional:configserver:classpath:/config/

server:
  port: 8085

# Actuator Configuration
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      access: read_only
    metrics:
      access: read_only